### ISSUE TITLE
Last TODO

### ISSUE THREAD

**Issue by greta-avetisian** [cesare-spinoso/project_432#5]
- [x] Fix typos in :
  - [x] Electricity
  - [x] Outliers
  - [x] Time Series
  - [x] Linear Models
  - [x] Neural_networks
  - [x] Final Results
<br>

- [x] Rerun the following notebooks :
  - [x] Electricity
  - [x] Outliers
  - [x] Time Series
  - [x] Linear Models
    - [x] Remove hard coded lines if possible
    - [x] Delete Elastic Net Stuff
  - [x] Neural_networks
    - [x] Remove hard coded lines if possible (I didn't find any)
  - [x] Final Results
<br>

- [x] Overleaf:
  - [x] Add tables
  - [x] Update values in Report (aka results)
<br>

- [x] Video Presentation
  - [x] Update slides (including results)
  - [x] Rerecord sections
  - [x] Merge clips together
